### ISSUE TITLE
Update package descriptor after resource descriptor has been updated

### ISSUE THREAD

**Issue by simnh** [frictionlessdata/datapackage-py#213]
Hey, 

I want to automatically update resource descriptors, however, the descriptor of the whole package is not updated after I update the resource descriptor. 

For example:
```
p = Package('datapackage.json')
r = p.get_resource('r1')
r.descriptor = new_descriptor
r.commit()
p.commit()

r.descriptor # -> updated description
p.descriptor # -> still the old one 
```

Is there a way to make code like above work?

**Comment by zaneselvans** [comment]
I think I am also seeing this issue but in the context of an updated field descriptor that is failing to propagate upward into the table schema that the field is part of.

e.g.
```py
mines_table.schema.get_field('STATE').descriptor.update({'description': 'State abbreviation.'})
mines_table.schema.commit()
print(mines_table.schema.descriptor['fields'][10])
print(mines_table.schema.get_field('STATE').descriptor)
```
yields:
```py
{'name': 'STATE', 'type': 'string', 'format': 'default'}
{'name': 'STATE', 'type': 'string', 'format': 'default', 'description': 'State abbreviation.'}
```

**Comment by zaneselvans** [comment]
Upon some investigation, the field/table issue is a bit different than the resource/package issue, so I've created a new issue over in the `tableschema-py` repository:

https://github.com/frictionlessdata/tableschema-py/issues/217

**Comment by zaneselvans** [comment]
Looking at the code, there's not currently any infrastructure for altering an existing resource, and notifying the parent package about it. Caling `add_resource()` and `remove_resource()` both result in `package.__current_descriptor` being updated (the resource descriptor is appended to or deleted from the list of resources) and then `package.__build()` is called. So if the ordering of resources within the data package isn't important, then one solution might be to use `p.get_resource('r1')` make your edits, and then remove and re-add it to the package -- but this would result in the resource then being at the end of the list of resources.

Alternatively, since it seems like there will be a lot of updating existing resources that needs to happen in the course of fixing and adding on to any attributes which are inferred, and since folks do seem to be referring to resources based on their location in the list of resources, maybe there needs to be a `package.update_resource.()` method that works like the add/remove methods, except that it updates the existing resource in place and re-builds the package, preserving the resource ordering.

As it is right now it seems like you have to start at the lowest level in the overall hierarchy of descriptors, and work your way up -- define a bunch of fields, and add them to a schema. Use the schema to make a table. Use the table to make a resource, and add that resource to a package.  Then start over with the fields from the next table. I had thought the usage pattern was more meant to be infer a bunch of stuff from the files that will make up the data, hopefully getting a correct collection of metadata, then go in and clean it up or add to it a bit.

**Comment by roll** [comment]
@zaneselvans 
Not sure I fully understand. Our target in this issue is to make a package's descriptor updated after a resource's descriptor change.

We have this method:

> resource.py

```
    def commit(self, strict=None):
        """https://github.com/frictionlessdata/datapackage-py#resource
        """
        if strict is not None:
            self.__strict = strict
        elif self.__current_descriptor == self.__next_descriptor:
            return False
        self.__current_descriptor = deepcopy(self.__next_descriptor)
        self.__table = None
        self.__build()
        return True
```

To achieve our goal as I see it we only need to make changes like these:


```
    def commit(self, strict=None):
        """https://github.com/frictionlessdata/datapackage-py#resource
        """
        if strict is not None:
            self.__strict = strict
        elif self.__current_descriptor == self.__next_descriptor:
            return False
        self.__current_descriptor = deepcopy(self.__next_descriptor)
        self.__table = None
        self.__build()

        # find the index of the resource in self.__package.descriptor (or get the index in the constructor)
        # self._package.descriptor['resources'][index] = self.__current_descriptor
        # self._package.commit()

        return True
```

And this should be it. Shouldn't it?

**Comment by roll** [comment]
> But package.add_resource() (and the package itself) don't have access to the Resource object so it can't set resource.package -- add_resource() just takes a descriptor.

Yes, of course. I mean it requires some complex approach. I should be easy to implement but still: a few updates here, a few updates there etc.

In high-level, yes, the intended approach for this iteration (focused on data publishers) was like:
- infer metadata from data
- tweak it by hands (saving/editing descriptor) or via raw `package.descriptor` 
- commit changes and save the data package 

So for now, more complex editing API is not really established.

**Comment by roll** [comment]
It's been fixed in [Frictionless Framework](https://github.com/frictionlessdata/tableschema-py#tableschema-py) as the whole working with metadata design was re-worked
