### ISSUE TITLE
Python's CSV only accepts 'lineTerminator' as '\r\n', '\n' or '\r'

### ISSUE THREAD

**Issue by vitorbaptista** [frictionlessdata/datapackage-py#58]
According to the CSV Dialect at http://dataprotocols.org/csv-dialect/, an user can pass any character sequence as a `lineTerminator` when parsing a CSV file. Unfortunately, Python's CSV reader module only accepts `\r\n` or `\n` as `lineTerminator`.

We need to, at minimum, warn the user, and preferably fix the issue. We could replace the `lineTerminator` for `\n` in the CSV text whenever we detect the dialect is set to something different than what's supported by Python.

**Comment by roll** [comment]
@rgrp 
@pwalsh 
WDYT?

I've added warning and following discussion may be better to have in `specs` tracker. Because current situation is Python will not be supporting `lineTerminator` in foreseeable future. And it's a core language for the stack. Support it on dp level in my opinion will lead to many problems. So may be better to remove it from spec to do not confuse users? I'm not sure how useful to have something instead of `\r\n`, `\r` or `\n` for line breaks.

**Comment by pwalsh** [comment]
I think we should change the spec to require line terminator as one of \r\n, \r or \n

It is not just about Python's CSV implementation - the situation will be fairly the same across most programming languages, so not point in a spec feature that can't be implemented.

**Comment by rgrp** [comment]
@pwalsh +1 on limiting this. Not necessarily in CSV DDF but in Tabular Data Package spec. I don't think it will be a bit imposition ...
